package com.decagon.mobifind.utils

const val PICK_IMAGE = 1
const val AUTH_SIGN_IN = 1123
const val AUTH_SIGN_UP = 1124
const val LOCATION_PERMISSION_REQUEST_CODE = 1
const val GET_LOCATION_UPDATE = 2356
const val LOCATION_UPDATE_STATE = 23
const val REQUEST_READ_CONTACT = 123
const val SIGN_UP_FIREBASE = 2234
const val LOG_IN_FIREBASE = 11056
const val ACTION_START_OR_RESUME_SERVICE = "ACTION_START_OR_RESUME_SERVICE"
const val ACTION_PAUSE_SERVICE = "ACTION_PAUSE_SERVICE"
const val ACTION_STOP_SERVICE = "ACTION_STOP_SERVICE"
const val NOTIFICATION_CHANNEL_ID = "tracking_channel"
const val NOTIFICATION_ID = 1
const val NOTIFICATION_CHANNEL_NAME = "Tracking"